// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5pY-cxNCCBcs-YZ1gyjqGT_32fAUc9k',
    appId: '1:304280003866:web:27634e7a071ff79df9f8a3',
    messagingSenderId: '304280003866',
    projectId: 'authentication-ed90e',
    authDomain: 'authentication-ed90e.firebaseapp.com',
    storageBucket: 'authentication-ed90e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT62h4nIkWIvz_WXlIvLNvbjXvTA7bUKU',
    appId: '1:304280003866:android:d1fbc95519fb9085f9f8a3',
    messagingSenderId: '304280003866',
    projectId: 'authentication-ed90e',
    storageBucket: 'authentication-ed90e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6pGG-51Qu7jiXECK_rftWmNb-fUGk8E',
    appId: '1:304280003866:ios:90a944f6540b1754f9f8a3',
    messagingSenderId: '304280003866',
    projectId: 'authentication-ed90e',
    storageBucket: 'authentication-ed90e.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6pGG-51Qu7jiXECK_rftWmNb-fUGk8E',
    appId: '1:304280003866:ios:90a944f6540b1754f9f8a3',
    messagingSenderId: '304280003866',
    projectId: 'authentication-ed90e',
    storageBucket: 'authentication-ed90e.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
